import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Nav/Nav";
import SmoothScroll from "@/components/SmoothScroll/SmoothScroll";
import localFont from "next/font/local";
import { ViewTransitions } from "next-view-transitions";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/providers/AuthProvider";
import { ModalProvider } from "@/context/ModalContext";
import { Sofia_Sans_Extra_Condensed } from "next/font/google";

import CustomCursor from "@/components/CustomCursor/CustomCursor";

const sofia = Sofia_Sans_Extra_Condensed({
  variable: "--sofia",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "800", "900"],
});

const NeueHaasGroteskBold = localFont({
  src: "../../public/fonts/NeueHaasGroteskBold.woff2",
  variable: "--NeueHaasGroteskBold",
  display: "swap",
});

const NeueHaasGroteskMedium = localFont({
  src: "../../public/fonts/NeueHaasGroteskMedium.woff2",
  variable: "--NeueHaasGroteskMedium",
  display: "swap",
});

const SuisseIntlCondensed = localFont({
  src: "../../public/fonts/SuisseIntlCondBold.woff2",
  variable: "--SuisseIntlCondensed",
  display: "swap",
});

const SuisseIntlMedium = localFont({
  src: "../../public/fonts/SuisseIntlMedium.woff2",
  variable: "--SuisseIntlMedium",
  display: "swap",
});

const SuisseIntlMonoRegular = localFont({
  src: "../../public/fonts/SuisseIntlMonoRegular.woff2",
  variable: "--SuisseIntlMonoRegular",
  display: "swap",
});

const FeatureDeckLight = localFont({
  src: "../../public/fonts/FeatureDeckLight.woff2",
  variable: "--FeatureDeckLight",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang='en'>
        <body
          className={`${NeueHaasGroteskBold.variable} ${NeueHaasGroteskMedium.variable} ${SuisseIntlCondensed.variable} ${SuisseIntlMedium.variable} ${SuisseIntlMonoRegular.variable} ${FeatureDeckLight.variable} ${sofia.variable}`}
        >
          <SmoothScroll>
            <Toaster
              position='top-right'
              toastOptions={{
                className: "toastFont",
              }}
            />
            <AuthProvider>
              <ModalProvider>
                <Nav />

                {children}
              </ModalProvider>
            </AuthProvider>
            <CustomCursor />
          </SmoothScroll>
        </body>
      </html>
    </ViewTransitions>
  );
}
